
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DbDiagram
{

using System;
    using System.Collections.Generic;
    
public partial class Discounts
{

    public long Id { get; set; }

    public string CustomerLevel { get; set; }

    public decimal Discounts1 { get; set; }

    public string ScoreRequire { get; set; }

}

}
