// <auto-generated />
namespace AirShopp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shopp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shopp));
        
        string IMigrationMetadata.Id
        {
            get { return "201703130618517_shopp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
